# Intern Portal — mock-data Flask backend

Learning prototype for FlutterFlow → Flask → Google Sheets. All sample records are fictional. **Use only fabricated names, emails, activities, and other fields. Never import real TLT user data.** Email validation restricts addresses to example.com/org/net; it cannot detect real names or sensitive free text.

## Run locally

From Terminal:

```sh
cd "$HOME/Desktop/Intern Portal"
python3 -m venv .venv
source .venv/bin/activate
python -m pip install -r requirements.txt
python app.py
```

Open http://127.0.0.1:5000/api/health or http://127.0.0.1:5000/api/interns.
The existing empty `.env` is preserved. Default `mock` mode requires no credentials, makes no Google requests, and resets its in-memory records each time the server restarts.

## Structure

- `app.py`: configuration, application factory, health endpoint, JSON errors.
- `routes/interns.py`, `routes/hours.py`: CRUD endpoints.
- `routes/common.py`: shared CRUD and validation.
- `services/google_sheets.py`: mock storage and optional Sheets adapter.
- `.env.example`: configuration template; `.env` and credentials are ignored by Git.
- `tests/test_api.py`: local API checks.

## API

| Method | Path | Result |
| --- | --- | --- |
| GET | `/api/health` | Backend mode and process health (not a Google connectivity check) |
| GET / POST | `/api/interns` | List / create |
| GET / PUT / DELETE | `/api/interns/<intern_id>` | Read / replace / delete |
| GET / POST | `/api/hours` | List / create |
| GET / PUT / DELETE | `/api/hours/<entry_id>` | Read / replace / delete |

POST and PUT require exactly the writable fields below; IDs are generated by the server and retained on update. Responses are JSON objects, or arrays for lists. Creation returns 201, deletion 204, invalid input 400, missing IDs 404, and deleting an intern with hours returns 409.

```sh
curl -X POST http://127.0.0.1:5000/api/interns \
  -H 'Content-Type: application/json' \
  -d '{"name":"Jane Doe","email":"jane@example.com","program":"Mock Training","status":"Active"}'

curl -X POST http://127.0.0.1:5000/api/hours \
  -H 'Content-Type: application/json' \
  -d '{"intern_id":"INT001","date":"2026-09-01","hours":2,"activity":"Mock training exercise"}'
```

Status must be Active or Inactive. Hours must be numeric, greater than zero and at most 24. Dates use YYYY-MM-DD. Intern references must exist. Delete related hours before deleting an intern.

## Optional Google Sheets connection

1. Create a Google Cloud test project, enable the Google Sheets API, and create an OAuth 2.0 Client ID with application type **Desktop app**. Keep its downloaded JSON file in `credentials/` (ignored by Git); never upload it into FlutterFlow or commit it.
2. Create a **new, dedicated dummy-data spreadsheet** owned by the Google account you will authorize.
3. Add tabs with these exact names and header rows in A1:E1:

   - `Interns`: `intern_id`, `name`, `email`, `program`, `status`
   - `Hours`: `entry_id`, `intern_id`, `date`, `hours`, `activity`

4. Copy the settings from `.env.example` into `.env`. Set `STORAGE_BACKEND=sheets`, `MOCK_SHEET_CONFIRMED=true`, `GOOGLE_SHEET_ID` to the ID from the spreadsheet URL, `GOOGLE_AUTH_MODE=oauth`, `GOOGLE_OAUTH_CLIENT_FILE` to the downloaded client JSON path, and `GOOGLE_OAUTH_TOKEN_FILE` to an ignored local token path such as `credentials/oauth-token.json`. Restart Flask. The first run opens Google authorization in your browser; approve access using the account that owns the dummy spreadsheet. Later runs refresh the saved token automatically.
5. Create fake records through the API, then use the returned intern ID when creating hours. Sheets mode does not automatically seed or overwrite a sheet. The list endpoint checks headers on first access.

Writes use `RAW` to store strings literally. Deletes clear that record's A:E cells, leaving an empty row. The sheet must contain only these tables, with unique IDs and no manual edits while requests run. This adapter is a single-process teaching prototype: it lacks transactions and coordination across servers or external sheet edits.

## Tests and next steps

```sh
python -m unittest discover -s tests -v
```

Tests exercise mock CRUD, validation, and relationship protection. A live Sheets connection needs your own test credentials and has not been verified by these tests.

Next, connect FlutterFlow API calls to these routes and map the JSON fields. A browser frontend needs explicitly configured CORS for its actual origin; a phone needs a reachable backend address rather than the phone's localhost. Before exposing the server, add application user authentication and authorization and use a production deployment setup. Google service-account authentication only authorizes Flask to access Sheets; it does not authenticate portal users. No CORS or user authentication is included in this local scaffold.

References: [Flask application factories](https://flask.palletsprojects.com/en/stable/patterns/appfactories/), [Google Sheets values API](https://developers.google.com/workspace/sheets/api/guides/values).
